title = 'Learning Cloud Native Go'
baseURL = 'https://learning-cloud-native-go.github.io/'

defaultContentLanguage = 'en'
languageCode = 'en-us'

enableGitInfo = true

theme = 'docura'

markup.highlight.noClasses = false

[services]
[services.googleAnalytics]
ID = 'G-H3GD0XFJ42'