title = 'Learning Cloud Native Go'
baseURL = 'https://learning-cloud-native-go.github.io'

defaultContentLanguage = 'en'
languageCode = 'en-us'

googleAnalytics = 'G-H3GD0XFJ42'

enableGitInfo = true

theme = 'docura'

markup.highlight.noClasses = false