description = 'Cloud Native Go Tutorials for Everyone!'

author = 'Dumindu Madunuwan'
authorURL = 'https://github.com/dumindu'

facebookURL = ''
twitterURL = ''
githubURL = 'https://github.com/learning-cloud-native-go'
youtubeURL = ''

githubRepo = 'learning-cloud-native-go/site'
githubSponsorURL = 'https://github.com/sponsors/dumindu'
buyMeACoffeeURL = 'https://www.buymeacoffee.com/dumindu'

hugoURL = 'https://gohugo.io/'
docuraURL = 'https://docura.github.io/'

[algolia]
[algolia.en]
container = '#site-header-search'
appId = ''
indexName = 'learning-cloud-native-go'
apiKey = '9f66d24134e08e8c577683743bfb1918'
