description = 'Cloud Native Go Tutorials for Everyone!'

author = 'Dumindu Madunuwan'
authorURL = 'https://github.com/dumindu'

facebookURL = ''
twitterURL = ''
githubURL = 'https://github.com/learning-cloud-native-go'
youtubeURL = ''

githubRepo = 'learning-cloud-native-go/site'
githubSponsorURL = 'https://github.com/sponsors/dumindu'
buyMeACoffeeURL = 'https://www.buymeacoffee.com/dumindu'

[algolia]
[algolia.en]
container = '#site-header-search'
appId = '5ND7WIN6JB'
indexName = 'learning-cloud-native-go'
apiKey = '66b4409582624e8c99c5f15a4c13cd87'

[[githubRepos]]
name = 'Website'
repo = 'learning-cloud-native-go/site'
icon = "<i class='icon icon-repo-website'></i>"
description = 'The repository of the documentation.'

[[githubRepos]]
name = 'Code'
repo = 'learning-cloud-native-go/myapp'
icon = "<i class='icon icon-repo-code'></i>"
description = 'The repository of the API app.'
